❗️ВНИМАНИЕ #домашка №5
dedsher/ESoft-fifth-task pull request #1
Opened 2024-04-30 19:07 UTC by dedsher

2024-05-12 11:48 UTC, dedsher commented on src/App.tsx
Насчет Index.tsx как корневого рута:
По ТЗ главная страница /films, но я не понял, как сделать корневой url /films, поэтому корневой урл Index.tsx "/", и по переходу на "Все фильмы" отображается урл /films
Ко всему это решило мои противоречия с использованием аутлета

2024-05-13 08:42 UTC, dedsher commented on src/components/Search/SearchForm/SearchForm.tsx
Баг: у каждой карточки фильма есть список кнопок-жанров, нажав на какую-либо, закидывается в хранилище выбранный жанр и происходит переход на страницу поиска (Реализация в компоненте https://github.com/dedsher/ESoft-fifth-task/blob/d066033fcfa60a84420a03e7f02c361573089942/src/components/Genre/Genre.tsx ). Что-то начинает идти не так в момент маунта формы поиска, когда ей передается initialValue.

Сейчас я уже понимаю, что стоило изначально использовать searchParams.

Основной функционал работает как надо. Доп. функционал в виде перехода по жанру фильма работает не совсем как надо. Думаю, не будет проблемой переделать на searchParams в домашке по TS

2024-05-21 13:04 UTC, dedsher commented on src/api/filmsApi.ts
Разделяем запрос по названию и запрос по жанрам

2024-05-21 13:06 UTC, dedsher commented on src/components/FilmCard/FilmCardPreview/FilmCardPreview.tsx
до: браузер запрашивает постер фильма с сервера апишки, получает отказ, так как мы в России, отображает alt текст img
после: браузер запрашивает постер фильма с сервера апишки, получает отказ, так как мы в России, отображает картинку-заглушку
ну и с впн все изображения как загружались, так и загружаются

2024-05-21 13:07 UTC, dedsher commented on src/components/Genre/Genre.tsx
будем использовать useSearchParams

2024-05-21 13:14 UTC, dedsher commented on src/components/Search/SearchForm/SearchForm.tsx
Все выше фигня👆 все решил, все разрулил, рома один звонок, рома реакт. 

- Парсим поисковую строку
- Корректно используем initialValues в formik
- Корректно сабмитим и ресетим форму
- Вы прекрасны

2024-05-25 19:10 UTC, Unaccommodating requested changes
Мне нравится твоя работа! Есть пару правок, которые нужно внести

2024-05-25 19:10 UTC, Unaccommodating commented on src/api/filmsApi.ts
> +  console.log(`Предыдущий ключ: ${API_KEY}`);
после отладки и дебага не забывай удалять console.log

2024-05-25 19:10 UTC, Unaccommodating commented on src/api/filmsApi.ts
> +  if (data.message && data.message.includes("израсходовали")) {
а если не придёт ответ вообще? нужно обработка ошибок

2024-05-25 19:10 UTC, Unaccommodating commented on src/components/FilmCard/FilmCardInfo/FilmCardInfo.tsx
> +  };
```
type FilmShortInfoProps = Pick<Film, 'name' | 'rating' | 'genres' | 'persons' | 'shortDescription'>;

const FilmShortInfo: React.FC<FilmShortInfoProps> = ({ name, rating, genres, persons, shortDescription }) => {
  const getRatingColor = (imdb: number | undefined): string => {
    if (imdb === undefined) return "gray";
    if (imdb >= 7) return "green";
    if (imdb >= 5) return "orange";
    return "gray";
  };
```

2024-05-25 19:10 UTC, Unaccommodating commented on src/components/FilmCard/FilmCardInfo/FilmCardInfo.tsx
> +  }
```
const parsedGenres = useMemo(() => {
    return genres.length > 0 ? genres.map((genre) => genre.name) : ["Жанр не указан"];
  }, [genres]);

  const parsedPersons = useMemo(() => {
    const names = persons.length > 0 ? persons.map((person) => person.name).filter((name) => name) : ["Актеры не указаны"];
    return names.length > 3 ? names.slice(0, 3) : names;
  }, [persons]);
```

2024-05-25 19:10 UTC, Unaccommodating commented on src/components/FilmCard/FilmCardInfo/FilmCardInfo.tsx
> +  }
для кэширования значений `parsedGenres` и `parsedPersons`, чтобы они не пересчитывались при каждом рендере, если не изменились входные данные.

2024-05-25 19:10 UTC, Unaccommodating commented on src/pages/FilmAbout/FilmAbout.tsx
> +      {status === "loading" && <div>Loading...</div>}
если loader часто используется в проекте, то почему не вынес его в отдельную компоненту?)

2024-05-25 19:10 UTC, Unaccommodating commented on src/components/Tabs/Tabs.tsx
> +            }
```
className={`${styles.tab} ${item.value === currentFilter ? styles.tab_active : ""}`}
```

шаблонные строки

2024-05-28 14:07 UTC, dedsher commented on src/components/Tabs/Tabs.tsx
> +            }
@Unaccommodating сэр все поправил сэр

2024-06-03 18:16 UTC, merged